spring.datasource.url=jdbc:postgresql://localhost:5432/socialmedia
spring.datasource.username=devvk
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate

spring.liquibase.enabled=true
spring.liquibase.change-log=db/dbchangelog.xml

spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.threads.virtual.enabled=true

socialmedia.openapi.dev-url=http://localhost:8080
socialmedia.openapi.prod-url=https://mydomen.com
springdoc.swagger-ui.tryItOutEnabled=true
